apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins/jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins/jenkins 
  template:
    metadata:
      labels:
        app: jenkins/jenkins
    spec:
      containers:
      - name: jenkins/jenkins
        image: jenkins/jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  ports:
  - name: http
    port: 8080           
    targetPort: 8080   
  selector:
    app: jenkins/jenkins          
  type: LoadBalancer   
